name: clang-format compliance

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -yqq update && sudo apt-get -yqq install --no-install-recommends gnupg2 software-properties-common wget 
      - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17 main'
      - run: sudo apt-get -yqq update && sudo apt-get -yqq install clang-format-17
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run checker on code
        run: find ${{ github.workspace }} -name fmod -prune -iname *.h -o -iname *.hpp -o -iname *.c -o -iname *.cpp -o -iname *.cuh -o -iname *.cu | xargs clang-format -i
      - name: Run git diff to see if anything changed
        run: git diff --name-only --exit-code
      - name: Run git diff if we failed
        if: failure()
        run: git diff > diff
      - name: Archive diff if we failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: diff
          path: |
            ${{ github.workspace }}/diff
